# Generated by Django 5.0.6 on 2025-09-29 18:41

import django.db.models.deletion
import django.utils.timezone
import entregas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('token', models.CharField(default='', editable=False, max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data', models.DateField(default=entregas.models.default_hoje)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='entregas.funcionario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='retirada',
            constraint=models.UniqueConstraint(fields=('funcionario', 'data'), name='uma_retirada_por_dia'),
        ),
    ]
